---
buffrem:
- 0
- 40
jobtype: INT
jobname: 아크메이지불/독
vEnhanceNum: 13
preEmptiveSkills: 2
passive_skill_list:
- name: High Wisdom | 하이 위즈덤
  stat_main: 40
- name: Spell Mastery | 스펠 마스터리
  att: 10
- name: Arcane Overdrive | 매직 크리티컬
  crit: 30
  crit_damage: 13
- name: Element Amplification | 엘리멘트 엠플리피케이션
  pdamage: 50
- name: Elemental Decrease | 엘리멘탈 리셋
  pdamage_indep: 40
- name: Buff Mastery | 마스터 매직
  att: 30 + 3 * passive_level
  buff_rem: 50 + 5 * passive_level
- name: Arcane Aim | 아케인 에임
  armor_ignore: 20 + math.ceil(passive_level / 2)
not_implied_skill_list:
- name: Weapon Constant | 무기상수
  pdamage_indep: 20
- name: Mastery | 숙련도
  mastery: 95
- name: Burning Magic | 익스트림 매직
  pdamage_indep: 20
- name: Arcane Aim | 아케인 에임(Real Time | 실시간)
  pdamage: 40
- name: Fervent Drain | 퍼번트 드레인
  pdamage_indep: 25
- name: Elemental Decrease | 엘리멘탈 리셋(Use | 사용)
  prop_ignore: 10
constant:
  DOT_PUNISHER_HIT: 22
  ERUPTION_RATE:
  - 0
  - 0
  - 20
  - 45
  - 80
  - 125
skills:
  DoT Punisher | 도트 퍼니셔:
    type: DamageSkill
    delay: 690
    damage: 400 + 15 * lv
    tier: 5
    use_priority: 0
    upgrade_priority: 0
    hit: 5
    cooltime: 25000
    red: true
  Meditation | 메디테이션:
    type: BuffSkill
    delay: 0
    remain: 240000
    att: 30
    rem: true
    red: true
  Epic Adventure | 에픽 어드벤처:
    type: BuffSkill
    cooltime: 120000
    delay: 0
    red: false
    rem: false
    remain: 60000
    pdamage: 10
  Paralyze | 페럴라이즈:
    type: DamageSkill
    delay: 600
    damage: 220 + 3 * combat
    hit: 8
    modifier:
      pdamage: 10
    enhanced_by_v: true
    upgrade_priority: 1
    v_increment: 2
    v_crit: false
  Teleport Mastery | 텔레포트 마스터리:
    cooltime: -1
    delay: 0
    red: false
    rem: false
    enhanced_by_v: true
    upgrade_priority: 9
    v_increment: 3
    v_crit: true
    damage: 272
    hit: 1
    type: DamageSkill
  Flame Haze | 플레임 헤이즈:
    cooltime: 10000
    delay: 1080
    red: true
    rem: false
    damage: 202 + 3 * combat
    hit: 15
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 2
    v_increment: 2
    v_crit: true
  Mist Eruption | 미스트 이럽션:
    cooltime: 4000
    delay: 720
    red: true
    rem: false
    modifier:
      pdamage: 10
      pdamage_indep: ERUPTION_RATE[5]
      armor_ignore: 52.8
    damage: 45 + combat
    hit: 60
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 0
    v_increment: 2
    v_crit: false
  DoT Punisher | 도트 퍼니셔(Exceed | 초과):
    cooltime: 0
    delay: 0
    red: false
    rem: false
    modifier:
      pdamage_indep: -35
    tier: 5
    use_priority: 0
    upgrade_priority: 0
    damage: 400 + 15 * lv
    hit: 5 * (DOT_PUNISHER_HIT - 1)
    type: DamageSkill
  Poison Nova | 포이즌 노바:
    cooltime: 25000
    delay: 570
    red: true
    rem: false
    damage: 250 + 10 * lv
    hit: 12
    type: DamageSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 1
  Poison Nova | 포이즌 노바(Erupt | 폭발):
    cooltime: 0
    delay: 0
    red: false
    rem: false
    damage: 225 + 9 * lv
    hit: 36
    type: DamageSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 1
  Poison Nova | 포이즌 노바(Erupt | 폭발)(Exceed | 초과):
    cooltime: 0
    delay: 0
    name: Poison Nova | 포이즌 노바(Erupt | 폭발)(Exceed | 초과)
    red: false
    rem: false
    modifier:
      pdamage_indep: -50
    damage: 495
    hit: 12
    type: DamageSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 1
  Poison Chain | 포이즌 체인:
    cooltime: 30000
    delay: 600
    red: true
    rem: false
    damage: 300 + 12 * lv
    hit: 4
    type: DamageSkill
    tier: 5
    use_priority: 0
    upgrade_priority: 0
  Poison Chain | 포이즌 체인(Addition | 중독):
    cooltime: -1
    delay: 1800
    red: false
    rem: false
    damage: 150 + 6 * lv
    hit: 6
    remain: 16199
    summondelay: 0
    type: SummonSkill
    tier: 5
    use_priority: 0
    upgrade_priority: 0
  Meteor Shower | 메테오:
    cooltime: 45000
    delay: 690
    red: true
    rem: false
    damage: 318
    hit: 12
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 5
    v_increment: 2
    v_crit: true
  Megiddo Flame | 메기도 플레임:
    cooltime: 50000
    delay: 690
    red: false
    rem: false
    damage: 420
    hit: 15
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 8
    v_increment: 2
    v_crit: true
  Ifrit | 이프리트:
    cooltime: 0
    delay: 3030
    red: false
    rem: false
    damage: 152
    hit: 3
    remain: 265000
    summondelay: 600
    type: SummonSkill
    enhanced_by_v: true
    upgrade_priority: 6
    v_increment: 2
    v_crit: false
  Inferno Aura | 파이어 오라:
    cooltime: 0
    delay: 3000
    red: false
    rem: false
    modifier:
      pdamage: -50
    damage: 400
    hit: 2
    remain: 999999999
    summondelay: 0
    type: SummonSkill
    enhanced_by_v: true
    upgrade_priority: 4
    v_increment: 2
    v_crit: true
  Elemental Fury | 퓨리 오브 이프리트:
    cooltime: 75000
    delay: 240
    red: true
    rem: false
    damage: 440
    hit: 6
    remain: 5999
    summondelay: 360
    type: SummonSkill
    tier: 5
    use_priority: 3
    upgrade_priority: 2
  Meteor Shower | 메테오(Passive | 패시브):
    cooltime: 0
    delay: 0
    red: false
    rem: false
    damage: 224
    hit: 0.6 + 0.02 * combat
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 5
    v_increment: 2
    v_crit: true
  Ignite | 이그나이트:
    cooltime: 0
    delay: 0
    red: false
    rem: false
    damage: 40
    hit: 4.5
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 3
    v_increment: 4
    v_crit: false
  Ignite | 이그나이트(Meteor Shower | 메테오):
    cooltime: 0
    delay: 0
    red: false
    rem: false
    damage: 40
    hit: 3 * 3 * 0.5 * (0.6 + 0.02 * combat)
    type: DamageSkill
    enhanced_by_v: true
    upgrade_priority: 3
    v_increment: 4
    v_crit: false
  Paralyze | 페럴라이즈(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 244
    hit: 1
    remain: 10000
    summondelay: 0
    type: DotSkill
  Poison Mist | 포이즌 미스트(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 301
    hit: 1
    remain: 12000
    summondelay: 0
    type: DotSkill
  Ifrit | 이프리트(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 143
    hit: 1
    remain: 4000
    summondelay: 0
    type: DotSkill
  Flame Haze | 플레임 헤이즈(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 203
    hit: 1
    remain: 20000
    summondelay: 0
    type: DotSkill
  Teleport Mastery | 텔레포트 마스터리(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 49
    hit: 1
    remain: 8000
    summondelay: 0
    type: DotSkill
  Poison Breath | 포이즌 브레스(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 60
    hit: 1
    remain: 20000
    summondelay: 0
    type: DotSkill
  Megiddo Flame | 메기도 플레임(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 700
    hit: 1
    remain: 60000
    summondelay: 0
    type: DotSkill
  DoT Punisher | 도트 퍼니셔(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 200 + 3 * lv
    hit: 1
    remain: 16000
    summondelay: 0
    type: DotSkill
    tier: 5
    use_priority: 0
    upgrade_priority: 0
  Poison Nova | 포이즌 노바(DoT | 도트):
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 300 + 12 * lv
    hit: 1
    remain: 20000
    summondelay: 0
    type: DotSkill
    tier: 5
    use_priority: 2
    upgrade_priority: 1
  Energy Bolt | 에너지 볼트:
    cooltime: 0
    delay: 630
    red: false
    rem: false
    damage: 309
    hit: 1
    type: DamageSkill
  Flame Orb | 플레임 오브:
    cooltime: 0
    delay: 630
    red: false
    rem: false
    damage: 301
    hit: 2
    type: DamageSkill
  Poison Breath | 포이즌 브레스:
    cooltime: 0
    delay: 600
    red: false
    rem: false
    damage: 180
    hit: 1
    type: DamageSkill
  Explosion | 익스플로젼:
    cooltime: 0
    delay: 690
    red: false
    rem: false
    damage: 405
    hit: 2
    type: DamageSkill
  Poison Mist | 포이즌 미스트:
    cooltime: 0
    delay: 1140
    red: false
    rem: false
    damage: 270
    hit: 1
    type: DamageSkill
  Viral Slime | 슬라임 바이러스:
    cooltime: -1
    delay: 1000
    red: false
    rem: false
    damage: 160
    hit: 1
    remain: 10000
    summondelay: 1680
    type: DotSkill
